--
-- Table structure for table `setting`
--

CREATE TABLE IF NOT EXISTS `setting` (
  `setting_id` int(11) NOT NULL AUTO_INCREMENT,
  `store_id` int(11) NOT NULL DEFAULT '0',
  `group` varchar(32) NOT NULL,
  `key` varchar(64) NOT NULL,
  `value` text NOT NULL,
  `serialized` tinyint(1) NOT NULL,
  PRIMARY KEY (`setting_id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=4422 ;

--
-- Dumping data for table `setting`
--

INSERT INTO `setting` (`store_id`, `group`, `key`, `value`, `serialized`) VALUES
(0, 'carousel', 'carousel_module', 'a:1:{i:0;a:9:{s:9:"banner_id";s:2:"11";s:5:"limit";s:1:"5";s:6:"scroll";s:1:"3";s:5:"width";s:2:"80";s:6:"height";s:2:"80";s:9:"layout_id";s:1:"1";s:8:"position";s:14:"content_bottom";s:6:"status";s:1:"0";s:10:"sort_order";s:2:"-1";}}', 1),
(0, 'featured', 'product', '', 0),
(0, 'featured', 'featured_product', '65,64,66,62,63', 0),
(0, 'featured', 'featured_module', 'a:1:{i:0;a:7:{s:5:"limit";s:2:"10";s:11:"image_width";s:3:"156";s:12:"image_height";s:3:"156";s:9:"layout_id";s:1:"1";s:8:"position";s:14:"content_bottom";s:6:"status";s:1:"1";s:10:"sort_order";s:1:"1";}}', 1),
(0, 'affiliate', 'affiliate_module', 'a:1:{i:0;a:4:{s:9:"layout_id";s:2:"10";s:8:"position";s:12:"column_right";s:6:"status";s:1:"1";s:10:"sort_order";s:1:"1";}}', 1),
(0, 'category', 'category_module', 'a:3:{i:0;a:4:{s:9:"layout_id";s:1:"3";s:8:"position";s:11:"column_left";s:6:"status";s:1:"1";s:10:"sort_order";s:1:"1";}i:1;a:4:{s:9:"layout_id";s:1:"2";s:8:"position";s:11:"column_left";s:6:"status";s:1:"1";s:10:"sort_order";s:1:"1";}i:2;a:4:{s:9:"layout_id";s:1:"1";s:8:"position";s:11:"column_left";s:6:"status";s:1:"1";s:10:"sort_order";s:1:"1";}}', 1),
(0, 'account', 'account_module', 'a:1:{i:0;a:4:{s:9:"layout_id";s:1:"6";s:8:"position";s:12:"column_right";s:6:"status";s:1:"1";s:10:"sort_order";s:1:"1";}}', 1),
(0, 'banner', 'banner_module', 'a:3:{i:0;a:7:{s:9:"banner_id";s:2:"11";s:5:"width";s:3:"280";s:6:"height";s:3:"192";s:9:"layout_id";s:1:"1";s:8:"position";s:11:"content_top";s:6:"status";s:1:"1";s:10:"sort_order";s:1:"2";}i:1;a:7:{s:9:"banner_id";s:2:"12";s:5:"width";s:3:"280";s:6:"height";s:3:"192";s:9:"layout_id";s:1:"1";s:8:"position";s:11:"content_top";s:6:"status";s:1:"1";s:10:"sort_order";s:1:"3";}i:2;a:7:{s:9:"banner_id";s:2:"13";s:5:"width";s:3:"280";s:6:"height";s:3:"628";s:9:"layout_id";s:1:"1";s:8:"position";s:11:"column_left";s:6:"status";s:1:"1";s:10:"sort_order";s:1:"4";}}', 1),
(0, 'slideshow', 'slideshow_module', 'a:1:{i:0;a:7:{s:9:"banner_id";s:2:"14";s:5:"width";s:4:" 580";s:6:"height";s:3:"404";s:9:"layout_id";s:1:"1";s:8:"position";s:11:"content_top";s:6:"status";s:1:"1";s:10:"sort_order";s:1:"1";}}', 1),
(0, 'lpbc', 'lpbc_module', 'a:5:{i:0;a:11:{s:11:"category_id";s:2:"17";s:2:"dm";s:6:"normal";s:7:"subcats";s:4:"none";s:4:"pmin";s:1:"1";s:5:"limit";s:1:"4";s:11:"image_width";s:3:"156";s:12:"image_height";s:3:"156";s:9:"layout_id";s:1:"1";s:8:"position";s:14:"content_bottom";s:6:"status";s:1:"1";s:10:"sort_order";s:1:"3";}i:1;a:11:{s:11:"category_id";s:2:"68";s:2:"dm";s:6:"normal";s:7:"subcats";s:5:"ctabs";s:4:"pmin";s:1:"1";s:5:"limit";s:1:"4";s:11:"image_width";s:3:"156";s:12:"image_height";s:3:"156";s:9:"layout_id";s:1:"1";s:8:"position";s:14:"content_bottom";s:6:"status";s:1:"1";s:10:"sort_order";s:1:"4";}i:2;a:11:{s:11:"category_id";s:2:"73";s:2:"dm";s:6:"normal";s:7:"subcats";s:4:"none";s:4:"pmin";s:1:"1";s:5:"limit";s:1:"8";s:11:"image_width";s:3:"156";s:12:"image_height";s:3:"156";s:9:"layout_id";s:1:"1";s:8:"position";s:14:"content_bottom";s:6:"status";s:1:"1";s:10:"sort_order";s:1:"6";}i:3;a:11:{s:11:"category_id";s:2:"72";s:2:"dm";s:6:"normal";s:7:"subcats";s:4:"none";s:4:"pmin";s:1:"1";s:5:"limit";s:1:"4";s:11:"image_width";s:3:"156";s:12:"image_height";s:3:"156";s:9:"layout_id";s:1:"1";s:8:"position";s:14:"content_bottom";s:6:"status";s:1:"1";s:10:"sort_order";s:1:"7";}i:4;a:11:{s:11:"category_id";s:2:"71";s:2:"dm";s:6:"normal";s:7:"subcats";s:4:"none";s:4:"pmin";s:1:"1";s:5:"limit";s:1:"4";s:11:"image_width";s:3:"156";s:12:"image_height";s:3:"156";s:9:"layout_id";s:1:"1";s:8:"position";s:14:"content_bottom";s:6:"status";s:1:"1";s:10:"sort_order";s:1:"8";}}', 1),
(0, 'config', 'config_image_cart_height', '47', 0),
(0, 'config', 'config_image_cart_width', '47', 0),
(0, 'config', 'config_image_wishlist_height', '47', 0),
(0, 'config', 'config_image_wishlist_width', '47', 0),
(0, 'config', 'config_image_compare_height', '90', 0),
(0, 'config', 'config_image_compare_width', '90', 0),
(0, 'config', 'config_image_related_height', '145', 0),
(0, 'config', 'config_image_related_width', '145', 0),
(0, 'config', 'config_image_additional_height', '250', 0),
(0, 'config', 'config_image_additional_width', '250', 0),
(0, 'config', 'config_image_product_height', '156', 0),
(0, 'config', 'config_image_product_width', '156', 0),
(0, 'config', 'config_image_popup_height', '500', 0),
(0, 'config', 'config_image_thumb_height', '250', 0),
(0, 'config', 'config_image_popup_width', '500', 0),
(0, 'config', 'config_image_thumb_width', '250', 0),
(0, 'config', 'config_image_category_height', '156', 0),
(0, 'config', 'config_image_category_width', '156', 0),
(0, 'filter', 'filter_module', 'a:1:{i:0;a:4:{s:9:"layout_id";s:1:"3";s:8:"position";s:11:"column_left";s:6:"status";s:1:"1";s:10:"sort_order";s:1:"3";}}', 1),
(0, 'latest', 'latest_module', 'a:1:{i:0;a:7:{s:5:"limit";s:1:"8";s:11:"image_width";s:2:"80";s:12:"image_height";s:2:"80";s:9:"layout_id";s:1:"1";s:8:"position";s:11:"column_left";s:6:"status";s:1:"1";s:10:"sort_order";s:1:"2";}}', 1),
(0, 'special', 'special_module', 'a:1:{i:1;a:7:{s:5:"limit";s:1:"4";s:11:"image_width";s:2:"80";s:12:"image_height";s:2:"80";s:9:"layout_id";s:1:"1";s:8:"position";s:11:"column_left";s:6:"status";s:1:"1";s:10:"sort_order";s:1:"1";}}', 1),
(0, 'gazal', 'gazal_all_addtocart_hover', '', 0),
(0, 'gazal', 'gazal_all_buttons_color', '', 0),
(0, 'gazal', 'gazal_all_addtocart', '', 0),
(0, 'gazal', 'gazal_details_button_color', '', 0),
(0, 'gazal', 'gazal_details_addtocart_hover', '', 0),
(0, 'gazal', 'gazal_details_addtocart', '', 0),
(0, 'gazal', 'gazal_boxheading_font_size', '25', 0),
(0, 'gazal', 'gazal_boxheading_font_family', 'Archivo Narrow', 0),
(0, 'gazal', 'gazal_price_font_size', '', 0),
(0, 'gazal', 'gazal_boxheading_font', 'Archivo+Narrow', 0),
(0, 'gazal', 'gazal_price_font_family', '', 0),
(0, 'gazal', 'gazal_price_font', '', 0),
(0, 'gazal', 'gazal_product_font_size', '', 0),
(0, 'gazal', 'gazal_product_font_family', '', 0),
(0, 'gazal', 'gazal_product_font', '', 0),
(0, 'gazal', 'gazal_menu_font_size', '19', 0),
(0, 'gazal', 'gazal_menu_font_family', 'Archivo Narrow', 0),
(0, 'gazal', 'gazal_menu_font', 'Archivo+Narrow', 0),
(0, 'gazal', 'gazal_category_font_size', '', 0),
(0, 'gazal', 'gazal_category_font_family', '', 0),
(0, 'gazal', 'gazal_category_font', '', 0),
(0, 'gazal', 'gazal_button_font_size', '', 0),
(0, 'gazal', 'gazal_button_font_family', '', 0),
(0, 'gazal', 'gazal_button_font', '', 0),
(0, 'gazal', 'gazal_body_font_size', '', 0),
(0, 'gazal', 'gazal_body_font_family', '', 0),
(0, 'gazal', 'gazal_body_font', '', 0),
(0, 'gazal', 'gazal_title_font_family', 'Archivo Narrow', 0),
(0, 'gazal', 'gazal_title_font', 'Archivo+Narrow', 0),
(0, 'gazal', 'facebook_bg_color', '', 0),
(0, 'gazal', 'gazal_footerlinks_color', '', 0),
(0, 'gazal', 'gazal_footer_info_color', '', 0),
(0, 'gazal', 'gazal_second_border_color', '', 0),
(0, 'gazal', 'gazal_first_border_color', '', 0),
(0, 'gazal', 'gazal_footerheaderswid_border', '', 0),
(0, 'gazal', 'gazal_footerheaderswid_bg', '', 0),
(0, 'gazal', 'gazal_footerheaderswid_color', '', 0),
(0, 'gazal', 'gazal_footerheaders_color', '', 0),
(0, 'gazal', 'gazal_footer_bottom_bg', '', 0),
(0, 'gazal', 'gazal_footer_bg', '#FCFCFC', 0),
(0, 'gazal', 'gazal_links_color', '', 0),
(0, 'gazal', 'gazal_bodytext_color', '', 0),
(0, 'gazal', 'gazal_title_color', '', 0),
(0, 'gazal', 'gazal_product_name_color', '', 0),
(0, 'gazal', 'gazal_other_oldprice_color', '', 0),
(0, 'gazal', 'gazal_price_color', '', 0),
(0, 'gazal', 'gazal_sale_bg', '', 0),
(0, 'gazal', 'gazal_product_border', '', 0),
(0, 'gazal', 'gazal_prodbcat_tab_link', '', 0),
(0, 'gazal', 'gazal_prodbcat_tab_bg_select', '', 0),
(0, 'gazal', 'gazal_prodbcat_tab_bg', '', 0),
(0, 'gazal', 'gazal_prodbcat_viewall', '', 0),
(0, 'gazal', 'gazal_prodbcat_title', '', 0),
(0, 'gazal', 'gazal_heading_tabs_border', '', 0),
(0, 'gazal', 'gazal_heading_tabs_bg', '', 0),
(0, 'gazal', 'gazal_heading_color', '', 0),
(0, 'gazal', 'gazal_heading_border', '', 0),
(0, 'gazal', 'gazal_heading_bg', '', 0),
(0, 'gazal', 'gazal_category_title', '', 0),
(0, 'gazal', 'gazal_category_link_color_hover', '', 0),
(0, 'gazal', 'gazal_category_link_color', '', 0),
(0, 'gazal', 'gazal_category_heading_color', '', 0),
(0, 'gazal', 'gazal_category_heading_border', '', 0),
(0, 'gazal', 'gazal_category_heading_bg', '', 0),
(0, 'gazal', 'gazal_search_border', '', 0),
(0, 'gazal', 'gazal_search_bg', '', 0),
(0, 'gazal', 'gazal_cart_desc_color', '', 0),
(0, 'gazal', 'gazal_cart_title_color', '', 0),
(0, 'gazal', 'gazal_smenuh_color', '', 0),
(0, 'gazal', 'gazal_smenu_color', '', 0),
(0, 'gazal', 'gazal_sub_menu_heading', '', 0),
(0, 'gazal', 'gazal_menu_color_hover', '', 0),
(0, 'gazal', 'gazal_menu_color', '', 0),
(0, 'gazal', 'gazal_menu_bg_links_hover', '', 0),
(0, 'gazal', 'gazal_menu_border', '', 0),
(0, 'gazal', 'gazal_menu_background', '', 0),
(0, 'gazal', 'gazal_block_desc_color', '', 0),
(0, 'gazal', 'gazal_block_title_color', '', 0),
(0, 'gazal', 'gazal_welcome_text_color', '', 0),
(0, 'gazal', 'gazal_thickbar_color', '', 0),
(0, 'gazal', 'gazal_background_color_cont', '', 0),
(0, 'gazal', 'gazal_custom_image_cont', '', 0),
(0, 'gazal', 'gazal_custom_pattern_cont', '', 0),
(0, 'gazal', 'gazal_background_color', '#EDEDED', 0),
(0, 'gazal', 'gazal_pattern_cont', 'none', 0),
(0, 'gazal', 'gazal_custom_pattern', '', 0),
(0, 'gazal', 'gazal_custom_image', '', 0),
(0, 'gazal', 'gazal_pattern_overlay', '21', 0),
(0, 'gazal', 'gazal_status', '1', 0),
(0, 'gazal', 'custom_css', 'a:2:{i:1;s:0:"";i:2;s:0:"";}', 1),
(0, 'gazal', 'option_slideshow', 'a:2:{i:1;s:6:"grid_6";i:2;s:6:"grid_6";}', 1),
(0, 'gazal', 'gazal_pay10_link', 'a:2:{i:1;s:0:"";i:2;s:0:"";}', 1),
(0, 'gazal', 'gazal_pay10_img', 'a:2:{i:1;s:0:"";i:2;s:0:"";}', 1),
(0, 'gazal', 'gazal_pay9_link', 'a:2:{i:1;s:0:"";i:2;s:0:"";}', 1),
(0, 'gazal', 'gazal_pay9_img', 'a:2:{i:1;s:0:"";i:2;s:0:"";}', 1),
(0, 'gazal', 'gazal_pay8_link', 'a:2:{i:1;s:0:"";i:2;s:0:"";}', 1),
(0, 'gazal', 'gazal_pay8_img', 'a:2:{i:1;s:0:"";i:2;s:0:"";}', 1),
(0, 'gazal', 'gazal_pay7_link', 'a:2:{i:1;s:0:"";i:2;s:0:"";}', 1),
(0, 'gazal', 'gazal_pay7_img', 'a:2:{i:1;s:0:"";i:2;s:0:"";}', 1),
(0, 'gazal', 'gazal_pay6_link', 'a:2:{i:1;s:0:"";i:2;s:0:"";}', 1),
(0, 'gazal', 'gazal_pay6_img', 'a:2:{i:1;s:0:"";i:2;s:0:"";}', 1),
(0, 'gazal', 'gazal_pay5_link', 'a:2:{i:1;s:0:"";i:2;s:0:"";}', 1),
(0, 'gazal', 'gazal_pay5_img', 'a:2:{i:1;s:0:"";i:2;s:0:"";}', 1),
(0, 'gazal', 'gazal_pay4_link', 'a:2:{i:1;s:0:"";i:2;s:0:"";}', 1),
(0, 'gazal', 'gazal_pay3_img', 'a:2:{i:1;s:0:"";i:2;s:0:"";}', 1),
(0, 'gazal', 'gazal_pay3_link', 'a:2:{i:1;s:0:"";i:2;s:0:"";}', 1),
(0, 'gazal', 'gazal_pay4_img', 'a:2:{i:1;s:0:"";i:2;s:0:"";}', 1),
(0, 'gazal', 'gazal_pay2_link', 'a:2:{i:1;s:0:"";i:2;s:0:"";}', 1),
(0, 'gazal', 'gazal_pay2_img', 'a:2:{i:1;s:0:"";i:2;s:0:"";}', 1),
(0, 'gazal', 'gazal_pay1_link', 'a:2:{i:1;s:0:"";i:2;s:0:"";}', 1),
(0, 'gazal', 'gazal_pay1_img', 'a:2:{i:1;s:0:"";i:2;s:0:"";}', 1),
(0, 'gazal', 'gazal_rss_link', 'a:2:{i:1;s:0:"";i:2;s:0:"";}', 1),
(0, 'gazal', 'gazal_skype_link', 'a:2:{i:1;s:0:"";i:2;s:0:"";}', 1),
(0, 'gazal', 'gazal_pinterest_link', 'a:2:{i:1;s:0:"";i:2;s:0:"";}', 1),
(0, 'gazal', 'gazal_linkedin_link', 'a:2:{i:1;s:0:"";i:2;s:0:"";}', 1),
(0, 'gazal', 'gazal_digg_link', 'a:2:{i:1;s:0:"";i:2;s:0:"";}', 1),
(0, 'gazal', 'gazal_dribbble_link', 'a:2:{i:1;s:0:"";i:2;s:0:"";}', 1),
(0, 'gazal', 'gazal_vimeo_link', 'a:2:{i:1;s:0:"";i:2;s:0:"";}', 1),
(0, 'gazal', 'gazal_flickr_link', 'a:2:{i:1;s:0:"";i:2;s:0:"";}', 1),
(0, 'gazal', 'gazal_twitter_link', 'a:2:{i:1;s:0:"";i:2;s:0:"";}', 1),
(0, 'gazal', 'gazal_google_link', 'a:2:{i:1;s:0:"";i:2;s:0:"";}', 1),
(0, 'gazal', 'gazal_youtube_link', 'a:2:{i:1;s:29:"http://youtube.com/expandcart";i:2;s:29:"http://youtube.com/expandcart";}', 1),
(0, 'gazal', 'token_secret', 'a:2:{i:1;s:45:"CtjuLb70sIVq9NjGASftWxi9aKP40n8lwrjmgcxP0gZ1N";i:2;s:45:"CtjuLb70sIVq9NjGASftWxi9aKP40n8lwrjmgcxP0gZ1N";}', 1),
(0, 'gazal', 'gazal_facebook_link', 'a:2:{i:1;s:35:"https://www.facebook.com/expandcart";i:2;s:35:"https://www.facebook.com/expandcart";}', 1),
(0, 'gazal', 'consumer_secrett', 'a:2:{i:1;s:43:"8MofCB63ISKsyhNkXmO8vSmHtJeJNw8QbCfAseF54s8";i:2;s:43:"8MofCB63ISKsyhNkXmO8vSmHtJeJNw8QbCfAseF54s8";}', 1),
(0, 'gazal', 'access_token', 'a:2:{i:1;s:50:"2261993468-XCRHKDXof8u3wCzxyoj61GJ47UwmSQoKLNpy8gC";i:2;s:50:"2261993468-XCRHKDXof8u3wCzxyoj61GJ47UwmSQoKLNpy8gC";}', 1),
(0, 'gazal', 'consumer_keyy', 'a:2:{i:1;s:22:"er9HmJ9fBGW5S6NFb4KeAg";i:2;s:22:"er9HmJ9fBGW5S6NFb4KeAg";}', 1),
(0, 'gazal', 'gazal_facebook_id', 'a:2:{i:1;s:10:"expandcart";i:2;s:10:"expandcart";}', 1),
(0, 'gazal', 'gazal_twitter_username', 'a:2:{i:1;s:10:"ExpandCart";i:2;s:10:"ExpandCart";}', 1),
(0, 'gazal', 'gazal_cus_img', 'a:2:{i:1;s:29:"data/Gazal/shipping-70x70.png";i:2;s:29:"data/Gazal/shipping-70x70.png";}', 1),
(0, 'gazal', 'gazal_shipping_text', 'a:2:{i:1;s:16:"Express Shipping";i:2;s:15:"شحن سريع";}', 1),
(0, 'gazal', 'gazal_shipping_last_text', 'a:2:{i:1;s:18:"Same Day Delivery ";i:2;s:33:"توصيل في نفس اليوم";}', 1),
(0, 'gazal', 'gazal_phone', 'a:2:{i:1;s:11:"01000000000";i:2;s:11:"01000000000";}', 1),
(0, 'gazal', 'gazal_phone_second', 'a:2:{i:1;s:11:"01111111111";i:2;s:11:"01111111111";}', 1),
(0, 'gazal', 'gazal_email', 'a:2:{i:1;s:14:"your@email.com";i:2;s:14:"your@email.com";}', 1),
(0, 'gazal', 'gazal_email_second', 'a:2:{i:1;s:14:"your@email.com";i:2;s:14:"your@email.com";}', 1),
(0, 'gazal', 'gazal_custom_widget_title', 'a:2:{i:1;s:8:"About Us";i:2;s:17:"عن المتجر";}', 1),
(0, 'gazal', 'gazal_footer_info_text', 'a:2:{i:1;s:182:"Write here about your company Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry''s standard dummy text ever since the 1500s.";i:2;s:453:"أكتب عن متجرك هنا. ان ألمّ كنقطة فعل, إذ والقرى للأراضي الإنذار، أسر. على هو دخول وإعلان إستعمل, ماذا إحتار الأرواح مع عدد, أما و رئيس الأمم سنغافورة. أي أمّا العناد وبالتحديد، عدد, مع تعديل مهمّات الأمريكية فصل. مع نهاية الحكومة الى, وبدون تاريخ دول ان.";}', 1),
(0, 'gazal', 'gazal_contact_img', 'a:2:{i:1;s:19:"data/Gazal/map2.png";i:2;s:19:"data/Gazal/map2.png";}', 1),
(0, 'gazal', 'gazal_address', 'a:2:{i:1;s:22:"Your Address Goes Here";i:2;s:24:"ضع عنوانك هنا";}', 1),
(0, 'gazal', 'gazal_fourthblock_desc', 'a:2:{i:1;s:23:"Pay in cash on delivery";i:2;s:41:"إدفع عندما يصلك المنتج";}', 1),
(0, 'gazal', 'gazal_fourthblock_title', 'a:2:{i:1;s:17:"Cash On Delivery ";i:2;s:28:"دفع عند التوصيل";}', 1),
(0, 'gazal', 'gazal_fourthblock_img', 'a:2:{i:1;s:21:"data/Gazal/block4.png";i:2;s:21:"data/Gazal/block4.png";}', 1),
(0, 'gazal', 'gazal_thirdblock_title', 'a:2:{i:1;s:11:"Call us Now";i:2;s:17:"إتصل الأن";}', 1),
(0, 'gazal', 'gazal_thirdblock_img', 'a:2:{i:1;s:21:"data/Gazal/block1.png";i:2;s:21:"data/Gazal/block1.png";}', 1),
(0, 'gazal', 'gazal_thirdblock_desc', 'a:2:{i:1;s:28:"Place here your phone number";i:2;s:31:"ضع رقم الهاتف هنا";}', 1),
(0, 'gazal', 'gazal_secondblock_img', 'a:2:{i:1;s:21:"data/Gazal/block3.png";i:2;s:21:"data/Gazal/block3.png";}', 1),
(0, 'gazal', 'gazal_secondblock_title', 'a:2:{i:1;s:20:"This is a demo store";i:2;s:23:"متجر إفتراضي";}', 1),
(0, 'gazal', 'gazal_secondblock_desc', 'a:2:{i:1;s:13:"Free Shipping";i:2;s:17:"شحن مجاني";}', 1),
(0, 'gazal', 'gazal_time_text', 'a:2:{i:1;s:37:"Saturday - Sunday From 10 am to 20 pm";i:2;s:70:"السبت إلى الأحد - من 10 صباحا حتى 20 مساءا";}', 1),
(0, 'gazal', 'gazal_firstblock_title', 'a:2:{i:1;s:20:"This is a demo store";i:2;s:23:"متجر إفتراضي";}', 1),
(0, 'gazal', 'gazal_firstblock_desc', 'a:2:{i:1;s:11:"SECURE SITE";i:2;s:15:"تصفح أمن";}', 1),
(0, 'gazal', 'gazal_firstblock_img', 'a:2:{i:1;s:21:"data/Gazal/block2.png";i:2;s:21:"data/Gazal/block2.png";}', 1);

-- --------------------------------------------------------

--
-- Table structure for table `extension`
--

CREATE TABLE IF NOT EXISTS `extension` (
  `extension_id` int(11) NOT NULL AUTO_INCREMENT,
  `type` varchar(32) NOT NULL,
  `code` varchar(32) NOT NULL,
  PRIMARY KEY (`extension_id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=440 ;

--
-- Dumping data for table `extension`
--

INSERT INTO `extension` (`type`, `code`) VALUES
('module', 'banner'),
('module', 'carousel'),
('module', 'category'),
('module', 'affiliate'),
('module', 'account'),
('module', 'featured'),
('module', 'bestseller'),
('module', 'slideshow'),
('module', 'ncategory'),
('module', 'special'),
('module', 'latest'),
('module', 'filter'),
('module', 'gazal'),
('module', 'lpbc'),
('module', 'news');