
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for eclookup
-- ----------------------------
TRUNCATE TABLE `eclookup`;

-- ----------------------------
-- Records of eclookup
-- ----------------------------
BEGIN;
INSERT INTO `eclookup`(LookUpKey, `Name`, `Value`, Lang, SortOrder) VALUES ('base-slides-textposition', 'Left', '1', 'en', 0),

('base-slides-textposition', 'Left', '1', 'en', 0),
('base-slides-textposition', 'Right', '2', 'en', 1),
('base-slides-textposition', 'Middle', '3', 'en', 2),
('base-slides-textposition', 'على اليسار', '1', 'ar', 0),
('base-slides-textposition', 'على اليمين', '2', 'ar', 1),
('base-slides-textposition', 'في المنتصف', '3', 'ar', 2),
('base-pbox-rows', '1', '1', 'en', 0),
('base-pbox-rows', '2', '2', 'en', 1),
('base-pbox-rows', '3', '3', 'en', 2),
('base-pbox-rows', '4', '4', 'en', 3),
('base-pbox-rows', '5', '5', 'en', 4),
('base-pbox-rows', '6', '6', 'en', 5),
('base-pbox-rows', '1', '1', 'ar', 0),
('base-pbox-rows', '2', '2', 'ar', 1),
('base-pbox-rows', '3', '3', 'ar', 2),
('base-pbox-rows', '4', '4', 'ar', 3),
('base-pbox-rows', '6', '6', 'ar', 4),
('base-banner-width', '25%', '1/4', 'en', 0),
('base-banner-width', '33.33%', '1/3', 'en', 1),
('base-banner-width', '50%', '1/2', 'en', 2),
('base-banner-width', '66.67%', '2/3', 'en', 3),
('base-banner-width', '75%', '3/4', 'en', 4),
('base-banner-width', '100%', '1', 'en', 5),
('base-banner-width', '25%', '1/4', 'ar', 0),
('base-banner-width', '33.33%', '1/3', 'ar', 1),
('base-banner-width', '50%', '1/2', 'ar', 2),
('base-banner-width', '66.67%', '2/3', 'ar', 3),
('base-banner-width', '75%', '3/4', 'ar', 4),
('base-banner-width', '100%', '1', 'ar', 5),
('base-box-width', '25%', '1/4', 'en', 0),
('base-box-width', '33.33%', '1/3', 'en', 1),
('base-box-width', '50%', '1/2', 'en', 2),
('base-box-width', '66.67%', '2/3', 'en', 3),
('base-box-width', '75%', '3/4', 'en', 4),
('base-box-width', '100%', 'color-maroon', 'en', 5),
('base-box-width', '25%', '1/4', 'ar', 0),
('base-box-width', '33.33%', '1/3', 'ar', 1),
('base-box-width', '50%', '1/2', 'ar', 2),
('base-box-width', '66.67%', '2/3', 'ar', 3),
('base-box-width', '75%', '3/4', 'ar', 4),
('base-box-width', '100%', '1', 'ar', 5),
('promo-color', 'color-red', 'color-red', 'en', 0),
('promo-color', 'color-purple', 'color-purple', 'en', 1),
('promo-color', 'color-blue', 'color-blue', 'en', 2),
('promo-color', 'color-maroon', 'color-maroon', 'en', 3),
('promo-color', 'color-yellow ', 'color-yellow ', 'en', 4),
('promo-color', 'color-cyan ', 'color-cyan ', 'en', 5),
('promo-color', 'لون احمر', 'color-red', 'ar', 0),
('promo-color', 'لون بنفسجي', 'color-purple', 'ar', 1),
('promo-color', 'لون ازرق', 'color-blue', 'ar', 2),
('promo-color', 'لون احمر داكن', 'color-maroon', 'ar', 3),
('promo-color', 'لون اصفر', 'color-yellow ', 'ar', 4),
('promo-color', 'لون سماوي', 'color-cyan', 'ar', 5),
('block-color', 'brown', 'color-brown', 'en', 1),
('block-color', 'blue', 'color-blue', 'en', 2),
('block-color', 'green', 'color-green', 'en', 3),
('block-color', 'purple', 'color-purple', 'en', 4),
('block-color', 'orange', 'color-orange', 'en', 5),
('block-color', 'brown', 'color-brown', 'ar', 1),
('block-color', 'blue', 'color-blue', 'ar', 2),
('block-color', 'green', 'color-green', 'ar', 3),
('block-color', 'purple', 'color-purple', 'ar', 4),
('block-color', 'orange', 'color-orange', 'ar', 5),
('text-align', 'right', 'info-right', 'en', 1),
('text-align', 'right', 'info-right', 'ar', 2),
('text-align', 'left', 'info-left', 'en', 3),
('text-align', 'left', 'info-left', 'ar', 4),

/* Arabic Fonts */
('ArabicFonts', 'Cairo Font', 'Cairo', 'en', 1),
('ArabicFonts', 'Cairo Font', 'Cairo', 'ar', 1),
('ArabicFonts', 'Changa Font', 'Changa', 'en', 2),
('ArabicFonts', 'Changa Font', 'Changa', 'ar', 2),
('ArabicFonts', 'Lateef Font', 'Lateef', 'en', 3),
('ArabicFonts', 'Lateef Font', 'Lateef', 'ar', 3),
('ArabicFonts', 'Amiri Font', 'Amiri', 'en', 4),
('ArabicFonts', 'Amiri Font', 'Amiri', 'ar', 4),
('ArabicFonts', 'Scheherazade Font', 'Scheherazade', 'en', 5),
('ArabicFonts', 'Scheherazade Font', 'Scheherazade', 'ar', 5),
('ArabicFonts', 'Next Font', 'Next', 'en', 6),
('ArabicFonts', 'Next Font', 'Next', 'ar', 6),

/* English Fonts */
('EnglishFonts', 'Roboto Font', 'Roboto', 'en', 1),
('EnglishFonts', 'Roboto Font', 'Roboto', 'ar', 1),
('EnglishFonts', 'Open Sans Font', 'Open Sans', 'en', 2),
('EnglishFonts', 'Open Sans Font', 'Open Sans', 'ar', 2),
('EnglishFonts', 'Raleway Font', 'Raleway', 'en', 3),
('EnglishFonts', 'Raleway Font', 'Raleway', 'ar', 3),
('EnglishFonts', 'Oxygen Font', 'Oxygen', 'en', 4),
('EnglishFonts', 'Oxygen Font', 'Oxygen', 'ar', 4),
('EnglishFonts', 'Work Sans Font', 'Work Sans', 'en', 5),
('EnglishFonts', 'Work Sans Font', 'Work Sans', 'ar', 5),
('EnglishFonts', 'Karla Font', 'Karla', 'en', 7),
('EnglishFonts', 'Karla Font', 'Karla', 'ar', 7),
('EnglishFonts', 'Ubuntu Font', 'Ubuntu', 'en', 8),
('EnglishFonts', 'Ubuntu Font', 'Ubuntu', 'ar', 8),

('layout', 'full width', 'full-width', 'en', 1),
('layout', 'عرض كامل', 'full-width', 'ar', 1),
('layout', 'Boxed', 'boxed', 'en', 2),
('layout', 'قالب صندوقي', 'boxed', 'ar', 2),
('layout', 'Normal', 'wide', 'en', 3),
('layout', 'قالب عادى', 'wide', 'ar', 3),

('FontAwesomeIcons', 'User', 'fa fa-user', 'en', 0),
('FontAwesomeIcons', 'Refresh', 'fa fa-refresh', 'en', 1),
('FontAwesomeIcons', 'Box', 'fa fa-archive', 'en', 2),
('FontAwesomeIcons', 'Basket', 'fa fa-shopping-basket', 'en', 3),
('FontAwesomeIcons', 'Shoping Bag', 'fa fa-shopping-bag', 'en', 4),
('FontAwesomeIcons', 'Truck', 'fa fa-truck', 'en', 5),
('FontAwesomeIcons', 'StreetView', 'fa fa-street-view', 'en', 6),
('FontAwesomeIcons', 'Location', 'fa fa-location-arrow', 'en', 7),
('FontAwesomeIcons', 'User', 'fa fa-user', 'ar', 0),
('FontAwesomeIcons', 'Refresh', 'fa fa-refresh', 'ar', 1),
('FontAwesomeIcons', 'Box', 'fa fa-archive', 'ar', 2),
('FontAwesomeIcons', 'Basket', 'fa fa-shopping-basket', 'ar', 3),
('FontAwesomeIcons', 'Shoping Bag', 'fa fa-shopping-bag', 'ar', 4),
('FontAwesomeIcons', 'Truck', 'fa fa-truck', 'ar', 5),
('FontAwesomeIcons', 'StreetView', 'fa fa-street-view', 'ar', 6),
('FontAwesomeIcons', 'Location', 'fa fa-location-arrow', 'ar', 7),
('blockFN', 'Latest Products', 'getLatestProducts', 'en', 1),
('blockFN', 'Best Selling Products', 'getBestSellerProducts', 'en', 2),
('blockFN', 'Special Products', 'getSpecialProducts', 'en', 3),
('blockFN', 'Category Products Products', 'getProductsByCategoryId', 'en', 4),
('blockFN', 'Featured Products', 'getFeaturedProducts', 'en', 5),
('blockFN', 'المنتجات الأحدث', 'getLatestProducts', 'ar', 1),
('blockFN', 'المنتجات الأفضل مبيعاً', 'getBestSellerProducts', 'ar', 2),
('blockFN', 'المنتجات ذات الخصومات', 'getSpecialProducts', 'ar', 3),
('blockFN', 'منتجات قسم محدد', 'getProductsByCategoryId', 'ar', 4),
('blockFN', 'منتجات مختارة', 'getFeaturedProducts', 'ar', 5);

COMMIT;

SET FOREIGN_KEY_CHECKS = 1;