/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `guide` (
  `UNIQUEID` int(11) NOT NULL AUTO_INCREMENT,
  `GUIDENAME` varchar(500) NOT NULL DEFAULT '',
  `KEY` varchar(500) NOT NULL DEFAULT '',
  `VALUE` varchar(500) NOT NULL DEFAULT '',
  PRIMARY KEY (`UNIQUEID`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;

INSERT INTO `guide` VALUES
(1,'MENU_TOUR','MENU_TOUR','0'),
(2,'GETTING_STARTED','GENERAL','0'),
(3,'GETTING_STARTED','EDIT_SETTINGS','0'),
(4,'GETTING_STARTED','CUST_DESIGN','0'),
(5,'GETTING_STARTED','ADD_PRODUCTS','0'),
(6,'GETTING_STARTED','UPGRADE_NOW','0'),
(7,'GETTING_STARTED','ADD_PRODUCTS','0'),
(8,'GETTING_STARTED','ADD_DOMAIN','0'),
(9,'GETTING_STARTED','PAYMENT','0'),
(10,'GETTING_STARTED','SHIPPING','0'),
(11,'GETTING_STARTED','LANGUAGE','0'),
(12,'GETTING_STARTED','CURRENCY','0'),
(13,'ASSISTANT','CUST_DESIGN','0'),
(14,'ASSISTANT','ADD_PRODUCTS','0'),
(15,'ASSISTANT','ADD_DOMAIN','0'),
(16,'ASSISTANT','GEO_ZONES','0'),
(17,'ASSISTANT','PAYMENT','0'),
(18,'ASSISTANT','SHIPPING','0'),
(19,'ASSISTANT','LANGUAGE','0'),
(20,'ASSISTANT','CURRENCY','0')
;