version: '2'

services:

  php-fpm:
    build: ./php-fpm
    volumes_from:
      - application
    expose:
      - "9000"
    extra_hosts:
      - "db:192.168.1.13"

  application:
    image: tianon/true
    volumes:
      - ../:/var/www/html

  apache:
    build: ./apache
    volumes_from:
      - application
    volumes:
      - ./logs/apache:/var/log/apache2
      - ./apache/sites:/etc/apache2/sites-available
    ports:
      - "80:80"
    depends_on:
      - php-fpm

